spitifi/spitifi/Controllers/MusicaController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using spitifi.Data;
using spitifi.Models;
using spitifi.Models.DbModels;

namespace spitifi.Controllers
{
    public class MusicaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public MusicaController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Musica
        public async Task<IActionResult> Index(
            int? pageNumber,
            int pageSize)
        {
            if (pageSize == 0)
            {
                pageSize = 5;
            }

            var applicationDbContext = _context.Musica.Include(m => m.Dono).Include(m => m.Album);

            // Create base query with includes
            var query = _context.Musica
                .Include(m => m.Dono)
                .Include(m => m.Album)
                .AsQueryable();

            // Apply pagination using Page.CreateAsync
            var paginatedResult = await Page<Musica>.CreateAsync(
                source: query,
                pageIndex: pageNumber ?? 1, // Default to page 1 if null
                pageSize: pageSize
            );
            return View(paginatedResult);
        }

        // GET: Musica/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musica = await _context.Musica
                .Include(m => m.Dono)
                .Include(m => m.Album)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (musica == null)
            {
                return NotFound();
            }

            return View(musica);
        }


        // GET: Musica/Create
        [Authorize(Roles = "Artista, Administrador")]
        public IActionResult Create()
        {
            ViewData["AlbumFK"] = new SelectList(_context.Album, "Id", "Titulo");
            ViewData["DonoFK"] = new SelectList(_context.Utilizadores, "Id", "Username");
            return View();
        }

        // POST: Musica/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Artista, Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,AlbumFK,DonoFK")] Musica musica,
            [Bind("Titulo")] Album album, List<IFormFile> musicaNova, IFormFile fotoAlbum)
        {
            ModelState.Remove("FilePath");

            if (ModelState.IsValid)
            {
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["DonoFK"] = new SelectList(_context.Utilizadores, "Id", "Username", musica.DonoFK);
            return View(musica);
        }


        // GET: Musica/Edit/5
        [Authorize(Roles = "Artista, Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musica = await _context.Musica.FindAsync(id);

            if (musica == null)
            {
                return NotFound();
            }

            var dono = _context.Utilizadores.FirstOrDefault(u => u.Id == musica.DonoFK);
            var album = _context.Album.FirstOrDefault(a => a.Id == musica.AlbumFK);

            ViewData["DonoNome"] = dono?.Username;
            ViewData["AlbumNome"] = album?.Titulo;
            return View(musica);
        }

        // POST: Musica/Edit/5
        [HttpPost]
        [Authorize(Roles = "Artista, Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, [Bind("Id,Nome,AlbumFK,DonoFK")] Musica musica,
            IFormFile musicaNova)
        {
            try
            {
                string nomeAudio = "";

                if (id != musica.Id)
                {
                    return RedirectToAction(nameof(Index));
                }

                var dono = await _context.Utilizadores.FindAsync(musica.DonoFK);

                if (dono.IdentityUser == null)
                {
                    // utilizador não pôde ser verificado
                    return RedirectToAction(nameof(Index));
                }

                // validar se quem tenta alterar a playlist é o dono or admin
                if (dono.IdentityUser != User.FindFirstValue(ClaimTypes.NameIdentifier) &&
                    !User.IsInRole("Administrador"))
                {
                    return Forbid();
                }

                var musicaAux = await _context.Musica.AsNoTracking().FirstOrDefaultAsync(m => m.Id == musica.Id);
                var antigoFicheiro = musicaAux.FilePath;

                if (id != musica.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        // se a imagem for diferente da default, vamos apagá-la do disco ao apagar a entrada da BD

                        if (musicaNova == null)
                            musica.FilePath = antigoFicheiro;
                        else
                        {
                            if (!musica.FilePath.Contains("smb_coin.wav"))
                            {
                                var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot",
                                    musica.FilePath);
                                // se o ficheiro/imagem existir apagamos
                                if (System.IO.File.Exists(oldFilePath))
                                    System.IO.File.Delete(oldFilePath);
                            }

                            if (!(musicaNova.ContentType == "audio/wav" || musicaNova.ContentType == "audio/mp3"))
                            {
                                ModelState.AddModelError("Ficheiro",
                                    "Ficheiro com extensão inválida, use wav ou mp3 por favor");
                                //Futuramente adicionar a PLayList
                                /*ViewData["CategoriaFk"] = new SelectList(_context.Musica, "Id", "Categoria",
                                    fotografia.CategoriaFk);*/
                                ViewData["DonoFk"] = new SelectList(_context.Utilizadores, "Id", "Nome", musica.DonoFK);
                                return View(musica);
                            }

                            //criar novo código unico
                            Guid g = Guid.NewGuid();
                            //buscar o novo codigo
                            nomeAudio = g.ToString();
                            //buscar o nome da foto (que ficou associado ao objeto do IFormFile)
                            string restoDoNome = Path.GetExtension(musicaNova.FileName).ToLowerInvariant();
                            nomeAudio += restoDoNome;
                            musica.FilePath = "imagens/" + nomeAudio;


                            // vai construir o path para o diretório onde são guardadas as imagens
                            var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot/imagens");

                            // antes de escrevermos o ficheiro, vemos se o diretório existe
                            if (!Directory.Exists(filePath))
                                Directory.CreateDirectory(filePath);

                            // atualizamos o Path para incluir o nome da imagem
                            filePath = Path.Combine(filePath, nomeAudio);

                            // escreve a imagem
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                await musicaNova.CopyToAsync(fileStream);
                            }
                        }

                        musica.Nome = Request.Form["Nome"];
                        _context.Update(musica);
                        await _context.SaveChangesAsync();
                    }
                    catch (Exception ex)
                    {
                    }

                    return RedirectToAction(nameof(Index));
                }

                ViewData["DonoNome"] = musica.Dono.Username;
                ViewData["AlbumNome"] = musica.Album.Titulo;

                return View(musica);
            }
            catch (Exception e)
            {
                return View();
            }
        }


        // GET: Musica/Delete/5
        [Authorize(Roles = "Artista, Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musica = await _context.Musica
                .Include(m => m.Dono)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (musica == null)
            {
                return NotFound();
            }

            return View(musica);
        }

        // POST: Musica/Delete/5
        [HttpPost, ActionName("Delete")] // Respond to view HTTP POST and map to asp-action "Delete"
        [Authorize(Roles = "Artista, Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {

spitifi/spitifi/Controllers/UtilizadoresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using spitifi.Data;
using spitifi.Models.DbModels;
using spitifi.Services.AlbumEraser;

namespace spitifi.Controllers
{
    public class UtilizadoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private AlbumEraser _AlbumEraser;
        private readonly UserManager<IdentityUser> _userManager;

        public UtilizadoresController(ApplicationDbContext context, AlbumEraser albumEraser, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _AlbumEraser = albumEraser;
            _userManager = userManager;
        }

        
        // GET: Utilizadores
        [Authorize(Roles="Administrador")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Utilizadores.ToListAsync());
        }

        // GET: Utilizadores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var utilizadores = await _context.Utilizadores
                .Include(u => u.Albums).ThenInclude(m => m.Musicas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        //Nova IAction para mostrar só os artistas aos ouvintes da webapp
        //Os admins terão acesso a todos os utilizadores
        public async Task<IActionResult> Artists()
        {
            return View(await _context.Utilizadores
                        .Where(a=> a.IsArtista == true)
                        .Include(a => a.Albums)
                            .ThenInclude(m => m.Musicas)
                        .ToListAsync());
        }

        // GET: Utilizadores/Create
        [Authorize(Roles="Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Utilizadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles="Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username")] Utilizadores utilizador)
        {
            if (ModelState.IsValid)
            {
                _context.Add(utilizador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(utilizador);
        }

        // GET: Utilizadores/Edit/5
        [Authorize(Roles="Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var utilizadores = await _context.Utilizadores.FindAsync(id);
            if (utilizadores == null)
            {
                return NotFound();
            }
            HttpContext.Session.SetInt32("utilizadorId", utilizadores.Id);
            return View(utilizadores);
        }

        // POST: Utilizadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles="Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute]int id, [Bind("Id,Username")] Utilizadores utilizador)
        {
            if (id != utilizador.Id)
            {
                return NotFound();
            }
            var utilizadorIdDaSessao = HttpContext.Session.GetInt32("utilizadorId");

            if (utilizadorIdDaSessao != id)
            {
                ModelState.AddModelError("", "Id inválido, por favor não mexa nas ferramentas do browser");
                return View(utilizador);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utilizador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilizadoresExists(utilizador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(utilizador);
        }

        // GET: Utilizadores/Delete/5
        [Authorize(Roles="Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utilizadores = await _context.Utilizadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utilizadores == null)
            {
                return NotFound();
            }

            return View(utilizadores);
        }

        // POST: Utilizadores/Delete/5
        [HttpPost, ActionName("Delete")] // Respond to view HTTP POST and map to asp-action "Delete"
        [Authorize(Roles="Administrador")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var utilizador = await _context.Utilizadores
                .Include(u => u.Albums)
                  .ThenInclude(u => u.Musicas)
                .Include(u => u.Playlists)
                .FirstOrDefaultAsync(u => u.Id == id);

            var utilizadorIdentity = await _userManager.FindByNameAsync(utilizador.Username);
            
            if (utilizador != null)
            {
                foreach (PlayList playList in utilizador.Playlists)
                {
                    _context.Remove(playList);
                }

                foreach (Album album in utilizador.Albums)
                {
                    await _AlbumEraser.AlbumEraserFunction(album.Id);
                }
                _context.Utilizadores.Remove(utilizador);
                await _context.SaveChangesAsync();
                
                await _userManager.DeleteAsync(utilizadorIdentity);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool UtilizadoresExists(int id)
        {
            return _context.Utilizadores.Any(e => e.Id == id);
        }

    }
}

spitifi/spitifi/Views/Musica/Create.cshtml
@model spitifi.Models.DbModels.Musica
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
}

<h1>Publicar uma Música</h1>

<h4></h4>
<p></p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input type="file" name="musicaNova" class="form-control"  multiple/>
                <span asp-validation-for="FilePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonoFK" class="control-label"></label>
                <select asp-for="DonoFK" class ="form-control" asp-items="ViewBag.DonoFK"></select>
                <span asp-validation-for="DonoFK" class="text-danger"></span>
            </div>
            <div>
                <!--
                <div>
                    <div class="form-check form-switch">
                        <input onchange="showHideAlbumFk()" class="form-check-input" type="checkbox" role="switch" name="albumExists" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Já existe o album?</label>
                    </div>
                </div>
                -->
                <div id="existsAlbum" class="form-group">
                    <label asp-for="AlbumFK" class="control-label"></label>
                    <select asp-for="AlbumFK" class="form-control" asp-items="ViewBag.AlbumFK"></select>
                    <span asp-validation-for="AlbumFK" class="text-danger"></span>
                </div>
                <!--
                <div id="createAlbum" class="form-group">
                    <label asp-for="Album.Titulo" class="control-label">Nome do Albúm</label>
                    <input asp-for="Album.Titulo" class="form-control"/>
                    <label asp-for="Album.Foto" class="control-label"></label>
                    <input type="file" name="fotoAlbum" class="form-control"/>
                    <span asp-validation-for="AlbumFK" class="text-danger"></span>
                </div>
                -->
            </div>
            
            <div class="form-group">
                <input type="submit" value="Publicar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

<script>
    /*
    const showHideAlbumFk = () => {
        $("#existsAlbum").toggle();
        $("#createAlbum").toggle();
    }
    */
</script>

spitifi/spitifi/Views/Musica/Delete.cshtml
@model spitifi.Models.DbModels.Musica
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Musica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dono.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

spitifi/spitifi/Views/Musica/Details.cshtml
@model spitifi.Models.DbModels.Musica
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Details";
    
    var dono = false;
    var userNameDono = Model.Dono.Username;
    if (User.Identity?.Name == userNameDono)
    {
        dono = true;
    }
}

<h1>Detalhes</h1>

<div>
    <h4>Musica</h4>
    <hr />
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nome)</th>
            <td>@Html.DisplayFor(model => model.Nome)</td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Album)</th>
            <td>@Html.DisplayFor(model => model.Album.Titulo)</td>
        </tr>
        <tr>
            <th>Foto do Álbum</th>
            <td>
                <img src="/@Model.Album.Foto" style="max-height: 50px; max-width: 50px"/>
            </td>
        </tr>
        <tr>
            <th>Audio</th>
            <td>
                <audio controls>
                    <source src="/@Model.FilePath" type="audio/wav">
                    <source src="/@Model.FilePath" type="audio/mp3">
                </audio>
            </td>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(model => model.DonoFK)</th>
            <td><a asp-controller="Utilizadores" asp-action="Details" asp-route-id="@Model.Dono.Id">@Html.DisplayFor(model => model.Dono.Username)</a></td>
        </tr>
    </table>
</div>
<div>
    <br/>
        <a asp-action="Index"><i class="bi bi-arrow-90deg-left" style="color: white"> Voltar </i></a>
    @if (dono || User.IsInRole("Administrador"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary" style="margin-right: 15px">Editar Música</a>
        <a asp-action="Delete" asp-route-id="@Model?.Id" class="btn btn-danger">Apagar Música</a>
    }

</div>

<script>

    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/likes")
        .configureLogging(signalR.LogLevel.Information)
        .withAutomaticReconnect()
        .build();

    async function start() {
        try {
            await connection.start();
            
            connection.on("whatever", (message) => {
                console.log(message)
            });


            console.log("SignalR Connected.");
        } catch (err) {
            console.log(err);
            setTimeout(start, 5000);
        }
    };
    
    // Start the connection.
    start();
    </script>

spitifi/spitifi/Views/Musica/Edit.cshtml
@model spitifi.Models.DbModels.Musica
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    
}

<h1>Editar</h1>

<h4>Musica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DonoFK" />
            <input type="hidden" asp-for="AlbumFK" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="AlbumFK" class="form-label">Albúm</label>
                <input class="form-control" value="@ViewData["AlbumNome"]" readonly />
                <span asp-validation-for="AlbumFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input type="file" name="musicaNova" class="form-control" />
                <span asp-validation-for="FilePath" class="text-danger"></span>
            </div>                            
            <div class="form-group mb-3">
                <label asp-for="DonoFK" class="form-label">Artista</label>
                <input class="form-control" value="@ViewData["DonoNome"]" readonly />
                <span asp-validation-for="DonoFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>