spitifi/spitifi/Controllers/AlbumController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using spitifi.Data;
using spitifi.Models;
using spitifi.Models.DbModels;
using spitifi.Services.AlbumEraser;

namespace spitifi.Controllers
{
    public class AlbumController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private AlbumEraser _AlbumEraser;

        public AlbumController(ApplicationDbContext context, UserManager<IdentityUser> userManager,
            IWebHostEnvironment webHostEnvironment, AlbumEraser albumEraser)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _AlbumEraser = albumEraser;
        }

        // GET: Album
        public async Task<IActionResult> Index(
            int? pageNumber,
            int pageSize)
        {
            if (pageSize == 0)
            {
                pageSize = 5;
            }

            var applicationDbContext = _context.Album
                .Include(m => m.Dono).ToList();

            // Create base query with includes
            var query = _context.Album.AsQueryable();

            // Apply pagination using Page.CreateAsync
            var paginatedResult = await Page<Album>.CreateAsync(
                source: query,
                pageIndex: pageNumber ?? 1, //página 1 caso pageNumber 0
                pageSize: pageSize
            );

            return View(paginatedResult);
        }

        // GET: Album/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
                .Include(a => a.Musicas)
                .Include(a => a.Dono)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Album/Create
        [Authorize(Roles = "Artista, Administrador")]
        public IActionResult Create()
        {
            var userId = _userManager.GetUserId(User);
            ViewData["DonoNome"] = _context.Utilizadores.FirstOrDefault(u => u.IdentityUser == userId).Username;
            return View();
        }

        // POST: Album/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "Artista, Administrador")]
        [RequestFormLimits(MultipartBodyLengthLimit = 100000000)] //~100Mb
        [RequestSizeLimit(100000000)] //~100Mb
        public async Task<IActionResult> Create([Bind("Id,Titulo")] Album album,
            IFormFile fotoAlbum, List<IFormFile> musicasNovas)
        {
            //variaveis para validações

            var identityUserId = _userManager.GetUserId(User);

            // encontrar username (Identity) do utilizador que fez o pedido, para poder associar ao utilizador local
            var utilizadorIdentity = _context.Users.First(au => au.UserName == User.Identity.Name);
            var utilizadorLocal = _context.Utilizadores.Where(u => u.IdentityUser == utilizadorIdentity.Id);

            bool haImagem = false;
            string nomeImagem = "";
            string nomeMusica = "";

            if (!utilizadorLocal.Any())
            {
                ModelState.AddModelError("DonoFK", "Alteração incorreta do Dono");
            }

            if (string.IsNullOrEmpty(album.Titulo))
            {
                ModelState.AddModelError("Titulo", "Não introduziste um título");
                ViewData["DonoNome"] =
                    _context.Utilizadores.FirstOrDefault(u => u.IdentityUser == identityUserId).Username;
                return View();
            }

            if (fotoAlbum == null)
            {
                ModelState.AddModelError("Foto", "Não introduziste uma foto");
                ViewData["DonoNome"] =
                    _context.Utilizadores.FirstOrDefault(u => u.IdentityUser == identityUserId).Username;
                return View();
            }

            if (musicasNovas.Count < 1)
            {
                ModelState.AddModelError("Musicas", "Não introduziste pelo menos uma musica/ficheiro");
                ViewData["DonoNome"] =
                    _context.Utilizadores.FirstOrDefault(u => u.IdentityUser == identityUserId).Username;
                return View();
            }

            //primeiro criaremos o album e a sua foto e depois as musicas
            if (ModelState.IsValid)
            {
                List<string> arrayPathMusicas = new List<string>();
                var fotoDeleteAlbum = "";

                try
                {
                    album.DonoFK = utilizadorLocal.First().Id;

                    foreach (var file in musicasNovas)
                    {
                        if (!file.ContentType.StartsWith("audio"))
                        {
                            ModelState.AddModelError("Musicas",
                                "Uma ou mais músicas com extensão inválida, use .wav ou .mp3 por favor");
                            ViewData["DonoNome"] = _context.Utilizadores
                                .FirstOrDefault(u => u.IdentityUser == identityUserId)
                                .Username;
                            return View();
                        }
                    }

                    if (!(fotoAlbum.ContentType == "image/png" || fotoAlbum.ContentType == "image/jpeg"))
                    {
                        ModelState.AddModelError("Foto", "Formato Inválido. Insira uma foto com formato JPEG ou PNG");
                        ViewData["DonoNome"] =
                            _context.Utilizadores.FirstOrDefault(u => u.IdentityUser == identityUserId).Username;
                        return View();
                    }

                    {
                        haImagem = true;
                        // gerar nome imagem
                        Guid g = Guid.NewGuid();
                        // atrás do nome adicionamos a pasta onde a escrevemos
                        nomeImagem = g.ToString();
                        string extensaoImagem = Path.GetExtension(fotoAlbum.FileName).ToLowerInvariant();
                        nomeImagem += extensaoImagem;
                        // guardar o nome do ficheiro na BD
                        album.Foto = "imagens/" + nomeImagem;
                    }

                    // se existe uma imagem para escrever no disco
                    if (haImagem)
                    {
                        // vai construir o path para o diretório onde são guardadas as imagens
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot/imagens");

                        // antes de escrevermos o ficheiro, vemos se o diretório existe
                        if (!Directory.Exists(filePath))
                            Directory.CreateDirectory(filePath);

                        // atualizamos o Path para incluir o nome da imagem
                        filePath = Path.Combine(filePath, nomeImagem);
                        //guardar o caminho da imagem para caso algo corra mal, possamos eliminar a foto da bd no nosso bloco de catch
                        fotoDeleteAlbum = filePath;

                        // escreve a imagem
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await fotoAlbum.CopyToAsync(fileStream);
                        }

                        //Criação das músicas
                        foreach (var formFile in musicasNovas)
                        {
                            // gerar nome imagem
                            Guid g = Guid.NewGuid();
                            // atrás do nome adicionamos a pasta onde a escrevemos
                            nomeMusica = g.ToString();
                            string extensaoMusica = Path.GetExtension(formFile.FileName).ToLowerInvariant();
                            nomeMusica += extensaoMusica;
                            // vai construir o path para o diretório onde são guardadas as imagens
                            var filePathMusica = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot/musicas");

                            // antes de escrevermos o ficheiro, vemos se o diretório existe
                            if (!Directory.Exists(filePathMusica))
                                Directory.CreateDirectory(filePathMusica);

                            // atualizamos o Path para incluir o nome da imagem
                            filePathMusica = Path.Combine(filePathMusica, nomeMusica);

                            // escreve a imagem
                            using (var fileStream = new FileStream(filePathMusica, FileMode.Create))
                            {
                                await formFile.CopyToAsync(fileStream);
                            }

                            //adicionar ao array para eliminar as musicas no bloco catch caso algo falhe na criação
                            arrayPathMusicas.Add(filePathMusica);

                            var novaMusica = new Musica
                                { DonoFK = album.DonoFK, Nome = formFile.FileName, FilePath = "musicas/" + nomeMusica };

                            album.Musicas.Add(novaMusica);

                            //usar o using para executar o bloco de código para executar aquela ação, é despejado assim que executado e não espera até ao final do controller

spitifi/spitifi/Controllers/ProcuraController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using spitifi.Data;
using spitifi.Models;
using spitifi.Services.AlbumEraser;

namespace spitifi.Controllers;

public class ProcuraController : Controller
{
    
    private readonly ApplicationDbContext _context;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly IWebHostEnvironment _webHostEnvironment;
    
    public ProcuraController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IWebHostEnvironment webHostEnvironment,  AlbumEraser albumEraser)
    {
        _context = context;
        _userManager = userManager;
        _webHostEnvironment = webHostEnvironment;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(string searchTerm)
    {
        var viewModel = new Procura() { TermoDeProcura = searchTerm };

        if (!string.IsNullOrWhiteSpace(searchTerm))
        {
            // procurar album
            viewModel.Albums = await _context.Album
                .Include(a => a.Dono)
                .Where(a => a.Titulo.Contains(searchTerm))
                .ToListAsync();

            // procurar musicas
            viewModel.Musicas = await _context.Musica
                .Include(m => m.Album)
                .Include(m => m.Dono)
                .Where(m => m.Nome.Contains(searchTerm))
                .ToListAsync();

            // Search Artists (only users marked as artists)
            // procurar artista
            viewModel.Artistas = await _context.Utilizadores
                .Where(u => u.IsArtista && u.Username.Contains(searchTerm))
                .ToListAsync();
        }

        return View(viewModel);
    }
}

spitifi/spitifi/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager

@{
    var currentUser = await UserManager.GetUserAsync(User);
    var isLoggedIn = currentUser != null;
    var isAdmin = isLoggedIn && await UserManager.IsInRoleAsync(currentUser, "Administrador");
    var isArtista = isLoggedIn && await UserManager.IsInRoleAsync(currentUser, "artista");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - spitifi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/spitifi.styles.css" asp-append-version="true"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
</head>
<body style="background-color: #666666; color: #ffffff">
<div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>

    <div class="p-3">
        <div>
            <img src="/assets/icons/spitifi.png" width="25" height="25">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"
               style="display: inline; color: #ffffff;">Spitifi</a>
        </div>
        <hr/>
        <div>
            <img src="/assets/icons/search.png" width="25" height="25">
            <a class="nav-link" asp-area="" asp-controller="Procura" asp-action="Index"
               style="display: inline;">Procurar</a>
        </div>
        <br/>
        <div>
            <img src="/assets/icons/music.png" width="25" height="25">
            <a class="nav-link" asp-area="" asp-controller="Musica" asp-action="Index"
               style="display: inline;">Mostrar Musicas</a>
        </div>
        <br>
        <div>
            <img src="/assets/icons/playlist.png" width="25" height="25">
            <a class="nav-link" asp-area="" asp-controller="Album" asp-action="Index"
               style="display: inline;">Mostrar Álbuns</a>
        </div>
        <br>
        <div>
            <img src="/assets/icons/playlist.png" width="25" height="25">
            <a class="nav-link" asp-area="" asp-controller="PlayList" asp-action="Index"
               style="display: inline;">Mostrar PlayLists</a>
        </div>
        <br>
        <div>
            <img src="/assets/icons/user.png" width="25" height="25">
            <a class="nav-link " asp-area="" asp-controller="Utilizadores" asp-action="Artists"
               style="display: inline;">Artistas</a>
        </div>
        <hr/>

        @if (isLoggedIn && !isAdmin)
        {
            <div>
                <img src="/assets/icons/add-to-playlist.png" width="25" height="25">
                <a class="nav-link" asp-area="" asp-controller="PlayList" asp-action="Create"
                   style="display: inline; padding-left: 32px;">Criar Playlist</a>
            </div>
            @if (isArtista)
            {
                <br>
                <div>
                    <img src="/assets/icons/add-to-playlist.png" width="25" height="25">
                    <a class="nav-link" asp-area="" asp-controller="Album" asp-action="Create"
                       style="display: inline;padding-left: 32px;">Criar Álbum</a>
                </div>
            }

            <hr/>
        }
        @if (isAdmin)
        {
            <div>
                <img src="/assets/icons/user.png" width="25" height="25">
                <a class="nav-link " asp-area="" asp-controller="Utilizadores" asp-action="Index"
                   style="display: inline;padding-left: 32px;">Utilizadores</a>
            </div>
            <hr/>
        }
        <partial name="_LoginPartial"/>
    </div>
</div>
<div class="main-content">
    <button id="buttonSideBar" class="openbtn" onclick="openNav()">☰</button>
    <!--Ao adicionar o css logo nesta div, como o render vem depois, podemos definir qual o max-width para todas as views e assim resolveu-se o problema de sobreposição da sidebar--->
    <main role="main" class="main-css">
        @RenderBody()
    </main>
</div>

<footer style="position: fixed; bottom: 0" class="border-top footer text-muted">
    
    <div id="audioContainer" class="container" style="background-color: #666666; ">
        <hr/>
        <div id="left">
            <img id="footerAlbumArt" src="" alt="Album Art" 
                 onerror="this.onerror=null; this.src='/assets/icons/musicPlaceholder.png'"/>
            <div class="song-info">
                <div id="footerSongName"></div>
                <div id="footerArtist"></div>
            </div>
        </div>
        
        <div id="middle">
            <div id="middleTop">
                <audio id="footerAudioPlayer" controls></audio>
            </div>
            <div id="middleBottom">
                <!-- Add icon inside the button -->
                <button id="musicaAnteriorBt"><i class="fas fa-step-backward"></i>
                    <img src="/assets/icons/left.png" width="25" height="25">
                </button>
                
                <button id="musicaSeguinteBt"><i class="fas fa-step-forward"></i>
                    <img src="/assets/icons/right.png" width="25" height="25">
                    </button>
            </div>
        </div>
        
        <div id="right" class="controls">
            <label>
                <input type="radio" name="playMode" value="once" checked> Dar play
            </label>
            <label>
                <input type="radio" name="playMode" value="loopTrack"> Loop Música
            </label>
            <label>
                <input type="radio" name="playMode" value="loopPlaylist"> Loop Playlist
            </label>
        </div>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
    //Script para abrir e fechar o menu lateral
    function openNav() {
        document.getElementById("mySidebar").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
    }

    // Update play/pause button icon
    document.addEventListener('play', function(e) {
        if (e.target.id === 'footerAudioPlayer') {
            document.querySelector('#playPauseBtn i').className = 'fas fa-pause';
        }
    }, true);

    document.addEventListener('pause', function(e) {
        if (e.target.id === 'footerAudioPlayer') {
            document.querySelector('#playPauseBtn i').className = 'fas fa-play';
        }
    }, true);
</script>